import { mkdirSync, readFileSync, writeFileSync, readdirSync, unlinkSync, copyFileSync, existsSync, chmodSync } from 'node:fs'
import { join, basename, extname } from 'node:path'
import { homedir } from 'node:os'

export class ConfigManager {
  constructor() {
    const configHome = process.env.XDG_CONFIG_HOME || join(homedir(), '.config')
    this.homeDir = join(configHome, 'cce')
    this.envsDir = join(this.homeDir, 'envs')
    this.defaultFile = join(this.homeDir, 'default')
    this.runtimeEnv = null

    this._ensureDirs()
  }

  _ensureDirs() {
    mkdirSync(this.envsDir, { recursive: true })
  }

  getCurrentEnvName() {
    if (this.runtimeEnv) return this.runtimeEnv
    if (process.env.CCE_ENV) return process.env.CCE_ENV
    if (existsSync(this.defaultFile)) {
      return readFileSync(this.defaultFile, 'utf8').trim()
    }
    return 'default'
  }

  setRuntimeEnv(name) {
    this.runtimeEnv = name
  }

  getRuntimeEnv() {
    return this.runtimeEnv || process.env.CCE_ENV || null
  }

  getDefaultEnv() {
    if (existsSync(this.defaultFile)) {
      return readFileSync(this.defaultFile, 'utf8').trim()
    }
    return 'default'
  }

  setDefaultEnv(name) {
    this._assertEnvExists(name)
    writeFileSync(this.defaultFile, name, 'utf8')
  }

  listEnvs() {
    try {
      return readdirSync(this.envsDir)
        .filter(f => f.endsWith('.env'))
        .map(f => f.slice(0, -4))
        .sort()
    } catch {
      return []
    }
  }

  _envPath(name) {
    return join(this.envsDir, `${name}.env`)
  }

  _assertEnvExists(name) {
    if (!existsSync(this._envPath(name))) {
      throw new Error(`environment '${name}' not found`)
    }
  }

  _parseEnvFile(content) {
    const result = {}
    for (const line of content.split('\n')) {
      const trimmed = line.replace(/#.*$/, '').trim()
      if (!trimmed) continue
      const eqIndex = trimmed.indexOf('=')
      if (eqIndex === -1) continue
      const key = trimmed.slice(0, eqIndex).trim()
      let val = trimmed.slice(eqIndex + 1).trim()
      // Remove surrounding quotes
      val = val.replace(/^["']|["']$/g, '')
      result[key] = val
    }
    return result
  }

  _buildEnvFile(options) {
    const lines = ['# Generated by cce']
    if (options.provider) lines.push(`CCE_PROVIDER=${options.provider}`)
    if (options.model) lines.push(`CCE_MODEL=${options.model}`)
    if (options.apiKey) lines.push(`ANTHROPIC_API_KEY=${options.apiKey}`)
    if (options.apiBase) lines.push(`ANTHROPIC_BASE_URL=${options.apiBase}`)
    if (options.claudeBin) lines.push(`CCE_CLAUDE_BIN=${options.claudeBin}`)
    if (options.extraEnv && options.extraEnv.length > 0) {
      lines.push(`CCE_EXTRA_ENV="${options.extraEnv.join(' ')}"`)
    }
    return lines.join('\n') + '\n'
  }

  loadEnv(name) {
    this._assertEnvExists(name)
    const content = readFileSync(this._envPath(name), 'utf8')
    const parsed = this._parseEnvFile(content)
    return {
      provider: parsed.CCE_PROVIDER || '',
      model: parsed.CCE_MODEL || '',
      apiKey: parsed.ANTHROPIC_API_KEY || '',
      apiBase: parsed.ANTHROPIC_BASE_URL || '',
      claudeBin: parsed.CCE_CLAUDE_BIN || '',
      extraEnv: parsed.CCE_EXTRA_ENV || '',
    }
  }

  get(key) {
    const name = this.getCurrentEnvName()
    const env = this.loadEnv(name)
    const keyMap = {
      provider: 'provider',
      model: 'model',
      apiKey: 'apiKey',
      apiBase: 'apiBase',
      claudeBin: 'claudeBin',
    }
    return env[keyMap[key]] || ''
  }

  createEnv(name, options) {
    if (existsSync(this._envPath(name))) {
      throw new Error(`environment '${name}' already exists`)
    }
    const content = this._buildEnvFile(options)
    writeFileSync(this._envPath(name), content, 'utf8')
    chmodSync(this._envPath(name), 0o600)
  }

  removeEnv(name) {
    this._assertEnvExists(name)
    unlinkSync(this._envPath(name))
    // If it was the default, reset
    if (this.getDefaultEnv() === name) {
      if (existsSync(this.defaultFile)) unlinkSync(this.defaultFile)
    }
  }

  importEnv(src) {
    if (!existsSync(src)) {
      throw new Error(`import file not found: ${src}`)
    }
    let base = basename(src, extname(src))
      .toLowerCase()
      .replace(/[^a-z0-9_-]/g, '')
    if (!base) base = 'imported'

    let target = this._envPath(base)
    if (existsSync(target)) {
      let i = 1
      while (existsSync(this._envPath(`${base}-${i}`))) i++
      target = this._envPath(`${base}-${i}`)
      base = `${base}-${i}`
    }
    copyFileSync(src, target)
    chmodSync(target, 0o600)
    return base
  }

  exportEnv(target, envName) {
    const name = envName || this.getCurrentEnvName()
    this._assertEnvExists(name)
    copyFileSync(this._envPath(name), target)
    chmodSync(target, 0o600)
  }
}
